// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQj5vbnPurx-y6DHKlSm5Bj3E7bgL7KnY',
    appId: '1:276350745055:web:eec58f922d93e307ce6c6a',
    messagingSenderId: '276350745055',
    projectId: 'tp-log-in',
    authDomain: 'tp-log-in.firebaseapp.com',
    storageBucket: 'tp-log-in.firebasestorage.app',
    measurementId: 'G-6MSQMF90QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdFC2HkKRthQ8SO_8ire2V3tiTJ6Uk_1w',
    appId: '1:276350745055:android:023580ad26d0491ece6c6a',
    messagingSenderId: '276350745055',
    projectId: 'tp-log-in',
    storageBucket: 'tp-log-in.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzxo-aBCwoRpJwdak4t2fNkXd1fzjsxks',
    appId: '1:276350745055:ios:07d947a8cb181f6bce6c6a',
    messagingSenderId: '276350745055',
    projectId: 'tp-log-in',
    storageBucket: 'tp-log-in.firebasestorage.app',
    iosBundleId: 'com.example.logIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzxo-aBCwoRpJwdak4t2fNkXd1fzjsxks',
    appId: '1:276350745055:ios:07d947a8cb181f6bce6c6a',
    messagingSenderId: '276350745055',
    projectId: 'tp-log-in',
    storageBucket: 'tp-log-in.firebasestorage.app',
    iosBundleId: 'com.example.logIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQj5vbnPurx-y6DHKlSm5Bj3E7bgL7KnY',
    appId: '1:276350745055:web:1977594ecefcac5cce6c6a',
    messagingSenderId: '276350745055',
    projectId: 'tp-log-in',
    authDomain: 'tp-log-in.firebaseapp.com',
    storageBucket: 'tp-log-in.firebasestorage.app',
    measurementId: 'G-RGZ68MXYFL',
  );

}